In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

In [23]:
df = pd.read_csv("EV_Data (1).csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,state,year,EV Registrations,Total Vehicles,EV Share (%),Stations,Total Charging Outlets,Level 1,...,personal,reducetax,regulate,worried,price_cents_per_kwh,gasoline_price_per_gallon,Total,Trucks,Trucks_Share,Party
0,0,0,Alabama,2023,13000,4835900,0.27,424,1096,35,...,39.06,62.16,69.01,54.95,11.47,2.742,5446619.0,3.397137e+06,62.37,Republican
1,1,1,Alaska,2023,2700,559800,0.48,65,124,3,...,43.28,65.38,71.61,62.49,21.41,3.594,680974.0,5.175250e+05,76.00,Republican
2,2,2,Arizona,2023,89800,6529000,1.38,1198,3506,9,...,46.92,64.73,73.19,64.32,12.19,3.278,6447062.0,3.868118e+06,60.00,Democratic
3,3,3,Arkansas,2023,7100,2708300,0.26,334,833,3,...,39.08,63.39,68.58,56.21,9.73,2.760,3338322.0,2.291924e+06,68.65,Republican
4,4,4,California,2023,1256600,36850300,3.41,16381,49433,648,...,53.19,72.08,76.30,71.24,24.87,4.731,31057329.0,1.675788e+07,53.96,Democratic

In [24]:
df['state'] = LabelEncoder().fit_transform(df['state'])

df['Party'] = df['Party'].map({
    'Democrat': 0,
    'Republican': 1})

In [25]:
X = df.drop(columns=['EV Registrations'])
y = df['EV Registrations']

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [28]:
y_pred = rf.predict(X_test)

In [29]:
mean_squared_error(y_test, y_pred)
r2_score(y_test, y_pred)

0.9571416827863721

In [34]:
pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
}).sort_values(by='Importance', ascending=False)

                                  Feature  Importance
10                                DC Fast    0.254523
6                                Stations    0.107092
15                     Education_Bachelor    0.102822
7                  Total Charging Outlets    0.087429
9                                 Level 2    0.084642
4                          Total Vehicles    0.069785
31                                  Total    0.064743
32                                 Trucks    0.052148
5                            EV Share (%)    0.042969
12                             Incentives    0.038174
30              gasoline_price_per_gallon    0.032170
14                       Population_20_64    0.009554
8                                 Level 1    0.007647
19                         Per_Cap_Income    0.006440
26                              reducetax    0.005211
3                                    year    0.004956
16        Labour_Force_Participation_Rate    0.004028
1                              Unnamed: 0    0.003561
29                    price_cents_per_kwh    0.003470
11                           fuel_economy    0.003166
13  Number of Metro Organizing Committees    0.002851
22                                discuss    0.002577
23                                    exp    0.001920
28                                worried    0.001707
33                           Trucks_Share    0.001299
0                            Unnamed: 0.1    0.000974
27                               regulate    0.000940
18                    Bachelor_Attainment    0.000708
21                                devharm    0.000596
24                         localofficials    0.000418
2                                   state    0.000395
20                          affectweather    0.000386
25                               personal    0.000351
17                      Unemployment_Rate    0.000346
34                                  Party    0.000000